export type Category = "platform" | "apps" | "games" | "yuuki" | "ml" | "research";

export interface Project {
  slug: string;
  name: string;
  description: string;
  url: string | null;
  screenshot: string | null; // path under /public/screenshots, or null
  onAiPlatform: boolean; // true if this app runs on the self-hosted AI platform
  category: Category;
  // Complete and working, but architected to run locally only (native app,
  // LAN-only tool, etc.) — will never get a public URL. Not the same as
  // unfinished; only set alongside `url: null` for genuinely-done projects.
  localOnly?: boolean;
  // Was live, deliberately taken down. Only set alongside `url: null`.
  archived?: boolean;
}

export const CATEGORIES: { id: Category; label: string; blurb: string }[] = [
  { id: "platform", label: "On Yuu v1.1", blurb: "Apps built on my self-hosted AI platform." },
  { id: "apps", label: "Apps & tools", blurb: "Products, dashboards, and utilities." },
  { id: "games", label: "Games & worlds", blurb: "Multiplayer games, RPGs, and 3D simulations." },
  { id: "yuuki", label: "Yuuki suite", blurb: "A family of experimental desktop-class web apps." },
  { id: "ml", label: "ML & AI engineering", blurb: "Frameworks, libraries, and from-scratch builds." },
  { id: "research", label: "Research", blurb: "Benchmarks and empirical studies, each with a write-up site." },
];

const shot = (slug: string) => `/screenshots/${slug}.webp`;

// Live URLs verified directly (curl'd 200 and page title checked against the
// project — several bare `<name>.vercel.app` domains belong to strangers), not
// guessed. Last full re-verification: 2026-09-14.
export const PROJECTS: Project[] = [
  // --- Running on the self-hosted AI platform (Yuu v1.1) ---
  { slug: "nodability", name: "Nodability", category: "platform", onAiPlatform: true,
    description: "AI-chat-driven personal task organizer for a couple, with task board and calendar views.",
    url: "https://nodability.vercel.app", screenshot: shot("nodability") },
  { slug: "daily-brief", name: "Daily Brief", category: "platform", onAiPlatform: true,
    description: "Personal daily-briefing app aggregating weather, news, sports, stocks, crypto, and more.",
    url: "https://daily-brief-lovat.vercel.app", screenshot: shot("daily-brief") },
  { slug: "dramabrief", name: "DramaBrief", category: "platform", onAiPlatform: true,
    description: "Daily briefing platform for Asian dramas, stars, music, and reality TV news.",
    url: "https://dramabrief.vercel.app", screenshot: shot("dramabrief") },
  { slug: "engo", name: "Engo", category: "platform", onAiPlatform: true,
    description: "Video-first language-learning platform teaching Japanese/English through real YouTube lessons.",
    url: "https://engo-peach.vercel.app", screenshot: shot("engo") },
  { slug: "market-brief", name: "Market Brief", category: "platform", onAiPlatform: true,
    description: "Personal finance-news dashboard with market, earnings/SEC, and AI/tech news plus a watchlist.",
    url: "https://market-brief-seven.vercel.app", screenshot: shot("market-brief") },
  { slug: "mindloop", name: "Mindloop", category: "platform", onAiPlatform: true,
    description: "Turns pasted notes into flashcards, adaptive quizzes, practice tests, and an AI tutor.",
    url: "https://mindloop-pink.vercel.app", screenshot: shot("mindloop") },
  { slug: "fluent", name: "FLUENT", category: "platform", onAiPlatform: true,
    description: "3D Tokyo life-sim for learning Japanese, with AI-driven NPC conversations.",
    url: "https://fluent-taupe-eight.vercel.app", screenshot: shot("fluent") },
  { slug: "ai-iceberg-web", name: "The AI Iceberg", category: "platform", onAiPlatform: true,
    description: "Ten interactive browser ports of an AI curriculum, from classical AI to agents, every algorithm written from scratch.",
    url: "https://theaiiceberg.vercel.app", screenshot: shot("ai-iceberg-web") },
  { slug: "trading-professor", name: "Trading Professor", category: "platform", onAiPlatform: true,
    description: "Educational swing-trading research platform and paper-trading coach, built with Streamlit.",
    url: "https://trading-professor-gary.fly.dev", screenshot: shot("trading-professor") },
  { slug: "atlasyuu", name: "AtlasYuu", category: "platform", onAiPlatform: true,
    description: "Travel command center - world map, couples journal, photo memory boards, and AI trip planning via Yuu.",
    url: "https://atlasyuu.vercel.app", screenshot: shot("atlasyuu") },
  { slug: "bite-map", name: "Bite Map", category: "platform", onAiPlatform: true,
    description: "Food exploration OS - interactive restaurant map, food journal, photo scrapbook, and an AI concierge.",
    url: "https://bite-map-lyart.vercel.app", screenshot: shot("bite-map") },
  { slug: "project-chatcut", name: "ChatCut", category: "platform", onAiPlatform: true,
    description: "Private fork of OpenChatCut, an AI-assisted, transcript-driven video editor.",
    url: "https://project-chatcut.fly.dev", screenshot: shot("project-chatcut") },
  { slug: "yuu-jarvis", name: "Yuu Jarvis", category: "platform", onAiPlatform: true,
    description: "Personal AI command system built on OpenJarvis for tracking concurrent Claude Code sessions.",
    url: "https://yuu-jarvis.vercel.app", screenshot: shot("yuu-jarvis") },

  // --- Apps & tools ---
  { slug: "lumina", name: "LUMINA", category: "apps", onAiPlatform: false,
    description: "Hang an artist's work in 141 real photographed rooms for auction listings, with a video compositor mode.",
    url: "https://lumina-two-rose.vercel.app", screenshot: shot("lumina") },
  { slug: "liveframe", name: "LIVEFRAME", category: "apps", onAiPlatform: false,
    description: "Real-time AI performance camera editor.",
    url: "https://liveframe-omega.vercel.app", screenshot: shot("liveframe") },
  { slug: "project-animos", name: "Animos", category: "apps", onAiPlatform: false,
    description: "Turn a screenshot into a polished animated product showcase, right in the browser.",
    url: "https://project-animos.vercel.app", screenshot: shot("project-animos") },
  { slug: "promptforge", name: "PromptForge", category: "apps", onAiPlatform: false,
    description: "Turns a one-sentence idea into a production-grade coding-agent prompt: architecture, schema, APIs, tests, and a build plan.",
    url: "https://promptforge-gamma-eight.vercel.app", screenshot: shot("promptforge") },
  { slug: "project-socialcards", name: "SocialCards", category: "apps", onAiPlatform: false,
    description: "Data-driven player cards generated from GitHub, Spotify, Discord, Instagram, and more.",
    url: "https://project-socialcards.vercel.app", screenshot: shot("project-socialcards") },
  { slug: "fitdrop", name: "FITDROP", category: "apps", onAiPlatform: false,
    description: "Short-term fashion rental - rent everyday clothing for tonight, the weekend, or the week.",
    url: "https://fitdrop-inky.vercel.app", screenshot: shot("fitdrop") },
  { slug: "scholarshell", name: "ScholarShell", category: "apps", onAiPlatform: false,
    description: "Chrome extension that turns any tab into a research workspace.",
    url: "https://scholarshell.vercel.app", screenshot: shot("scholarshell") },
  { slug: "meow-ai-agent", name: "MEOW AI Agent", category: "apps", onAiPlatform: false,
    description: "Personal AI agent for task triage, decision support, and a daily digest - a terminal that learned graphic design.",
    url: "https://meow-ai-agent.vercel.app", screenshot: shot("meow-ai-agent") },
  { slug: "doomscroll-tracker", name: "Doomscroll Tracker", category: "apps", onAiPlatform: false,
    description: "Webcam tool that opens a McDonald's job application whenever you look at your phone.",
    url: "https://doomscroll-tracker.vercel.app", screenshot: shot("doomscroll-tracker") },
  { slug: "chibi-links", name: "chibi", category: "apps", onAiPlatform: false,
    description: "Single-file serverless URL shortener.",
    url: "https://chibi-links-topaz.vercel.app", screenshot: shot("chibi-links") },
  { slug: "pixel-garden", name: "Pixel Garden", category: "apps", onAiPlatform: false,
    description: "Pixel-art habit tracker where your habits grow a garden.",
    url: "https://pixel-garden-inky.vercel.app", screenshot: shot("pixel-garden") },
  { slug: "helm", name: "Helm", category: "apps", onAiPlatform: false,
    description: "Personal command center / Life OS unifying school, career, research, and personal life into one ranked priority view.",
    url: "https://helm-lovat-theta.vercel.app", screenshot: shot("helm") },
  { slug: "latticework", name: "Latticework", category: "apps", onAiPlatform: false,
    description: "SWE/quant/ML learning platform with dozens of hands-on skills and a sandboxed code runner.",
    url: "https://latticework-gilt.vercel.app", screenshot: shot("latticework") },
  { slug: "yume", name: "Yume", category: "apps", onAiPlatform: false,
    description: "Persistent virtual hangout room for friend groups with voice/video, camera bubbles, and drawing.",
    url: "https://yume-gray.vercel.app", screenshot: shot("yume") },
  { slug: "hyperliquid-bot-web", name: "Hyperliquid Bot", category: "apps", onAiPlatform: false,
    description: "Read-only paper-trading dashboard mirroring an EMA-crossover strategy on live market data.",
    url: "https://hyperliquid-bot-web-alpha.vercel.app", screenshot: shot("hyperliquid-bot-web") },
  { slug: "sports-betting-web", name: "Sports Betting Scanner", category: "apps", onAiPlatform: false,
    description: "Password-gated scanner comparing sportsbook odds vs. prediction markets to flag +EV bets.",
    url: "https://sports-betting-web.vercel.app", screenshot: shot("sports-betting-web") },
  { slug: "edge-terminal", name: "Edge Terminal", category: "apps", onAiPlatform: false,
    description: "Prediction-market (Kalshi/Polymarket) +EV scanner and paper-trading terminal for sports markets.",
    url: "https://edge-terminal-fawn.vercel.app", screenshot: shot("edge-terminal") },
  { slug: "careeratlas", name: "CareerAtlas", category: "apps", onAiPlatform: false,
    description: "Interactive global job salary, career-transition, education-impact, and industry-trend tracker.",
    url: "https://careeratlas-ten.vercel.app", screenshot: shot("careeratlas") },
  { slug: "application-hq", name: "Application HQ", category: "apps", onAiPlatform: false,
    description: "Tracker for an entire grad-school and job-application pipeline, from prospects to offers.",
    url: "https://application-hq.vercel.app", screenshot: shot("application-hq") },
  { slug: "together-wellness", name: "Together Wellness", category: "apps", onAiPlatform: false,
    description: "Private app for a couple to connect Oura Ring accounts and share sleep/health data.",
    url: "https://together-wellness-mauve.vercel.app", screenshot: shot("together-wellness") },
  { slug: "pocket-vlog-web", name: "Pocket Vlog", category: "apps", onAiPlatform: false,
    description: "Group members capture daily moments that auto-assemble into a shared vlog at a cutoff time.",
    url: "https://pocket-vlog-web.vercel.app", screenshot: shot("pocket-vlog-web") },
  { slug: "full-house", name: "Full House", category: "apps", onAiPlatform: false,
    description: "Screen-scraping poker assistant for friendly, no-money home games.",
    url: "https://gariyuuu.github.io/full-house/", screenshot: shot("full-house") },
  { slug: "macmine-lab", name: "MacMine Lab", category: "apps", onAiPlatform: false,
    description: "Local, transparent Monero/RandomX mining laboratory and dashboard for Apple Silicon Macs.",
    url: "https://macmine-lab.vercel.app", screenshot: shot("macmine-lab") },
  { slug: "project-worldmonitor", name: "World Monitor", category: "apps", onAiPlatform: false,
    description: "Private fork of an open-source real-time global intelligence dashboard - news, geopolitical, and infrastructure monitoring.",
    url: "https://project-worldmonitor.vercel.app", screenshot: shot("project-worldmonitor") },
  { slug: "project-yuuki", name: "Yuuki", category: "apps", onAiPlatform: false,
    description: "Personalized fork of Project AIRI, an AI companion / virtual character app.",
    url: "https://project-yuuki.vercel.app", screenshot: shot("project-yuuki") },
  { slug: "session-os", name: "Session OS", category: "apps", onAiPlatform: false,
    description: "Local-first session tracker for concurrent Claude Code sessions across projects, terminals, and VS Code windows.",
    url: "https://session-os-landing.vercel.app", screenshot: shot("session-os") },
  { slug: "complete-shelf-demo", name: "Project Library", category: "apps", onAiPlatform: false,
    description: "3D interactive bookshelf portfolio site.",
    url: "https://project-library.vercel.app", screenshot: shot("complete-shelf-demo") },
  { slug: "click-to-send", name: "Click to Send", category: "apps", onAiPlatform: false,
    description: "Tiny single-page site that sends a message by email or Discord DM via a shared access code.",
    url: "https://click-to-send.vercel.app", screenshot: shot("click-to-send") },
  { slug: "phone-watchdog-web", name: "Phone Watchdog", category: "apps", onAiPlatform: false,
    description: "Webcam-based app using on-device ML to detect phone use and trigger a fullscreen alarm.",
    url: "https://phone-watchdog-web.vercel.app", screenshot: shot("phone-watchdog-web") },

  // --- Games & worlds ---
  { slug: "abyss", name: "ABYSS", category: "games", onAiPlatform: false,
    description: "3D generative dungeon RPG where every floor has a reason to exist.",
    url: "https://abyss-black-sigma.vercel.app", screenshot: shot("abyss") },
  { slug: "aetheria-towerbound", name: "AETHERIA: Towerbound", category: "games", onAiPlatform: false,
    description: "3D living-world anime-fantasy RPG with an original trapped-in-a-VR-MMO premise.",
    url: "https://aetheria-towerbound.vercel.app", screenshot: shot("aetheria-towerbound") },
  { slug: "everworld", name: "EVERWORLD", category: "games", onAiPlatform: false,
    description: "3D generative open-world fantasy RPG.",
    url: "https://everworld-iota.vercel.app", screenshot: shot("everworld") },
  { slug: "sakura-days", name: "Sakura Days", category: "games", onAiPlatform: false,
    description: "Living anime social-life RPG set in a Japanese coastal university town.",
    url: "https://sakura-days.vercel.app", screenshot: shot("sakura-days") },
  { slug: "timewalker", name: "TIMEWALKER", category: "games", onAiPlatform: false,
    description: "Stand in Edo, 1600 - an inhabited 3D historical world, not a museum.",
    url: "https://timewalker.vercel.app", screenshot: shot("timewalker") },
  { slug: "chronos", name: "CHRONOS", category: "games", onAiPlatform: false,
    description: "3D alternate-history engine - change a turning point and watch the world diverge.",
    url: "https://chronos-woad-three.vercel.app", screenshot: shot("chronos") },
  { slug: "second-dawn", name: "Second Dawn", category: "games", onAiPlatform: false,
    description: "3D generational civilization sim - a colony ship, 120 persistent colonists, and emergent history.",
    url: "https://second-dawn.vercel.app", screenshot: shot("second-dawn") },
  { slug: "genesis", name: "GENESIS", category: "games", onAiPlatform: false,
    description: "Persistent 3D artificial-civilization simulation with emergent citizens.",
    url: "https://genesis-kappa-five.vercel.app", screenshot: shot("genesis") },
  { slug: "two-hundred", name: "200", category: "games", onAiPlatform: false,
    description: "Artificial-society experiment - 200 autonomous minds, one persistent world, no script.",
    url: "https://200-society.vercel.app", screenshot: shot("two-hundred") },
  { slug: "unwritten-murder", name: "The Unwritten Murder", category: "games", onAiPlatform: false,
    description: "Detective game where the murders emerge from simulation instead of being scripted.",
    url: "https://unwritten-murder.vercel.app", screenshot: shot("unwritten-murder") },
  { slug: "one-degree", name: "ONE DEGREE", category: "games", onAiPlatform: false,
    description: "Butterfly-effect engine that propagates one small change through a causal world.",
    url: "https://one-degree-engine.vercel.app", screenshot: shot("one-degree") },
  { slug: "reality-fork", name: "Reality Fork", category: "games", onAiPlatform: false,
    description: "Live the life you didn't choose - a fictional plausibility simulator.",
    url: "https://reality-fork.vercel.app", screenshot: shot("reality-fork") },
  { slug: "fantasy-league", name: "Fantasy League", category: "games", onAiPlatform: false,
    description: "Multi-sport fantasy league app - draft and compete against 7 AI managers with distinct personas.",
    url: "https://fantasy-league-iota-six.vercel.app", screenshot: shot("fantasy-league") },
  { slug: "buildstrike-arena", name: "BuildStrike Arena", category: "games", onAiPlatform: false,
    description: "Fast browser-based 3D 1v1 build-and-shoot duel game against a bot or a friend.",
    url: "https://buildstrike-arena.vercel.app", screenshot: shot("buildstrike-arena") },
  { slug: "chamber-seven", name: "Chamber Seven", category: "games", onAiPlatform: false,
    description: "Real-time multiplayer shotgun-duel game inspired by Buckshot Roulette, with a Career Mode.",
    url: "https://chamber-seven-omega.vercel.app", screenshot: shot("chamber-seven") },
  { slug: "vantage-chess", name: "Vantage Chess", category: "games", onAiPlatform: false,
    description: "Original from-scratch online chess platform with 10 Stockfish bot personalities and variants.",
    url: "https://vantage-chess.vercel.app", screenshot: shot("vantage-chess") },
  { slug: "deckhouse", name: "Deckhouse", category: "games", onAiPlatform: false,
    description: "Social multiplayer card game hub - Hold'em, Blackjack, Baccarat, Dou Dizhu, and Old Maid, with friends or AI.",
    url: "https://deckhouse-three.vercel.app", screenshot: shot("deckhouse") },
  { slug: "voidshift", name: "Voidshift", category: "games", onAiPlatform: false,
    description: "Multiplayer social-deduction game in the spirit of Among Us, with full roles, maps, tasks, and AI players.",
    url: "https://voidshift-sigma.vercel.app", screenshot: shot("voidshift") },
  { slug: "sound-clash", name: "Sound Clash", category: "games", onAiPlatform: false,
    description: "Real-time multiplayer music-guessing party game - buzz in, name the song, steal points.",
    url: "https://sound-clash-nu.vercel.app", screenshot: shot("sound-clash") },
  { slug: "pocket-party", name: "Pocket Party", category: "games", onAiPlatform: false,
    description: "Browser-based multiplayer mini-game platform - no download or account needed, just a room code.",
    url: "https://pocket-party-eta.vercel.app", screenshot: shot("pocket-party") },
  { slug: "puzzle-rush", name: "Puzzle Rush", category: "games", onAiPlatform: false,
    description: "Twelve original daily logic, word, pattern, and memory puzzles - play solo, race a friend, or run a Speed Round.",
    url: "https://puzzle-rush-six.vercel.app", screenshot: shot("puzzle-rush") },
  { slug: "anime-sim", name: "ANIME//SIM", category: "games", onAiPlatform: false,
    description: "Story-driven 2D anime life simulator blending visual novel, social-strategy, and turn-based RPG.",
    url: "https://anime-sim-eta.vercel.app", screenshot: shot("anime-sim") },
  { slug: "heartbreak-academy", name: "Heart//Break Academy", category: "games", onAiPlatform: false,
    description: "Anime-psychological RPG with Undertale-style bullet-dodging combat and visual-novel dialogue.",
    url: "https://heartbreak-academy.vercel.app", screenshot: shot("heartbreak-academy") },
  { slug: "project-messenger", name: "Messenger", category: "games", onAiPlatform: false,
    description: "Tiny-planet exploration game - walk a curved world and carry hand-written messages between NPCs, with realtime multiplayer presence.",
    url: "https://project-messenger-gamma.vercel.app", screenshot: shot("project-messenger") },

  // --- Yuuki suite ---
  { slug: "yuuki-desktop", name: "Yuuki Desktop", category: "yuuki", onAiPlatform: false,
    description: "Experimental desktop environment where apps, files, tasks, people, and context behave as one.",
    url: "https://yuuki-desktop.vercel.app", screenshot: shot("yuuki-desktop") },
  { slug: "yuuki-social", name: "Yuuki Social", category: "yuuki", onAiPlatform: false,
    description: "Social network built around discovery and relationships rather than engagement.",
    url: "https://yuuki-social.vercel.app", screenshot: shot("yuuki-social") },
  { slug: "yuuki-rooms", name: "Yuuki Rooms", category: "yuuki", onAiPlatform: false,
    description: "Persistent rooms for the people you love - leave a note, pin a song, come back to what changed.",
    url: "https://yuuki-rooms.vercel.app", screenshot: shot("yuuki-rooms") },
  { slug: "yuuki-messenger", name: "Yuuki Messenger", category: "yuuki", onAiPlatform: false,
    description: "Realtime messaging and community platform with conversation memory.",
    url: "https://yuuki-messenger.vercel.app", screenshot: shot("yuuki-messenger") },
  { slug: "yuuki-mail", name: "Yuuki Mail", category: "yuuki", onAiPlatform: false,
    description: "Desktop-class email client.",
    url: "https://yuuki-mail.vercel.app", screenshot: shot("yuuki-mail") },
  { slug: "yuuki-notes", name: "Yuuki Notes", category: "yuuki", onAiPlatform: false,
    description: "Local-first knowledge environment - block editor, backlinks, canvas, graph, timeline, and study mode.",
    url: "https://yuuki-notes.vercel.app", screenshot: shot("yuuki-notes") },
  { slug: "yuuki-files", name: "Yuuki Files", category: "yuuki", onAiPlatform: false,
    description: "File manager that understands relationships, projects, versions, and meaning.",
    url: "https://yuuki-files.vercel.app", screenshot: shot("yuuki-files") },
  { slug: "yuuki-terminal", name: "Yuuki Terminal", category: "yuuki", onAiPlatform: false,
    description: "Simulated developer terminal with tabs, panes, command blocks, failure intel, and a command composer.",
    url: "https://yuuki-terminal.vercel.app", screenshot: shot("yuuki-terminal") },
  { slug: "yuuki-research-engine", name: "Yuuki Research Engine", category: "yuuki", onAiPlatform: false,
    description: "Evidence-first research workstation - question, plan, evidence, claims, contradictions, confidence, report.",
    url: "https://yuuki-research-engine.vercel.app", screenshot: shot("yuuki-research-engine") },
  { slug: "yuuki-simulation-lab", name: "Yuuki Simulation Lab", category: "yuuki", onAiPlatform: false,
    description: "Conversational Monte Carlo simulation sandbox.",
    url: "https://yuuki-simulation-lab.vercel.app", screenshot: shot("yuuki-simulation-lab") },
  { slug: "yuuki-benchmark-arena", name: "Yuuki Benchmark Arena", category: "yuuki", onAiPlatform: false,
    description: "Reproducible AI evaluation lab - what each model is good at, how reliable, how fast, and whether a new version regressed.",
    url: "https://yuuki-benchmark-arena.vercel.app", screenshot: shot("yuuki-benchmark-arena") },
  { slug: "yuuki-browser-agent-lab", name: "Yuuki Browser Agent Lab", category: "yuuki", onAiPlatform: false,
    description: "Controlled lab for testing, benchmarking, replaying, and debugging AI agents that operate web interfaces.",
    url: "https://yuuki-browser-agent-lab.vercel.app", screenshot: shot("yuuki-browser-agent-lab") },
  { slug: "yuuki-design-forge", name: "Yuuki Design Forge", category: "yuuki", onAiPlatform: false,
    description: "Design intelligence platform - design contracts, component vault, motion, typography, and anti-pattern audits.",
    url: "https://yuuki-design-forge.vercel.app", screenshot: shot("yuuki-design-forge") },
  { slug: "yuuki-code-intel", name: "Yuuki Code Intelligence", category: "yuuki", onAiPlatform: false,
    description: "Cross-repository structural code index and search across the whole portfolio.",
    url: "https://yuuki-code-intel.vercel.app", screenshot: shot("yuuki-code-intel") },

  // --- ML & AI engineering ---
  { slug: "tinytorch", name: "TinyTorch", category: "ml", onAiPlatform: false,
    description: "Reverse-mode autodiff deep-learning framework built from scratch on NumPy, verified against PyTorch.",
    url: "https://tinytorch.vercel.app", screenshot: shot("tinytorch") },
  { slug: "transformer-from-zero", name: "Transformer From Zero", category: "ml", onAiPlatform: false,
    description: "Decoder-only Transformer language model built from PyTorch tensor primitives - forward pass, training loop, and sampler.",
    url: "https://transformer-from-zero.vercel.app", screenshot: shot("transformer-from-zero") },
  { slug: "orchestrion", name: "orchestrion", category: "ml", onAiPlatform: false,
    description: "Multi-agent orchestration framework in raw Python - typed messages, budget reservations, replayable traces, no LangChain.",
    url: "https://orchestrion-one.vercel.app", screenshot: shot("orchestrion") },
  { slug: "navstack", name: "navstack", category: "ml", onAiPlatform: false,
    description: "Robot autonomy stack from the math up - mapping, Monte Carlo localization, A*/RRT planning, and exploration, no ROS.",
    url: "https://navstack.vercel.app", screenshot: shot("navstack") },
  { slug: "embodied", name: "embodied", category: "ml", onAiPlatform: false,
    description: "An LLM agent that drives a simulated robot through a typed tool boundary.",
    url: "https://embodied-agent.vercel.app", screenshot: shot("embodied") },
  { slug: "minivla", name: "minivla", category: "ml", onAiPlatform: false,
    description: "Language-conditioned pick-and-place in MuJoCo - perception, calibration, inverse kinematics, and closed-loop verification.",
    url: "https://minivla.vercel.app", screenshot: shot("minivla") },
  { slug: "rankforge", name: "RankForge", category: "ml", onAiPlatform: false,
    description: "Offline retrieval-then-ranking framework for recommendation and search, with leakage enforced as a runtime invariant.",
    url: "https://rankforge-gamma.vercel.app", screenshot: shot("rankforge") },
  { slug: "ml-service-blueprint", name: "ML Service Blueprint", category: "ml", onAiPlatform: false,
    description: "Open-source template taking a tabular model from training to a validated production service.",
    url: "https://ml-service-blueprint-site.vercel.app", screenshot: shot("ml-service-blueprint") },
  { slug: "fastinfer", name: "FastInfer", category: "ml", onAiPlatform: false,
    description: "ML inference benchmarking toolkit built around a dynamic batching scheduler and standard backend adapters.",
    url: "https://fastinfer.vercel.app", screenshot: shot("fastinfer") },
  { slug: "evalkit", name: "EvalKit", category: "ml", onAiPlatform: false,
    description: "LLM evaluation toolkit where judges are instruments that must be calibrated and CI gates fail loudly.",
    url: "https://evalkit-doc.vercel.app", screenshot: shot("evalkit") },
  { slug: "model-foundry", name: "Model Foundry", category: "ml", onAiPlatform: false,
    description: "Model-training toolkit that makes data leakage structurally hard rather than merely discouraged.",
    url: "https://model-foundry-doc.vercel.app", screenshot: shot("model-foundry") },
  { slug: "quantkit", name: "QuantKit", category: "ml", onAiPlatform: false,
    description: "Correctness-focused quantitative finance library for Python with lookahead-safe historical APIs.",
    url: "https://quantkit-docs.vercel.app", screenshot: shot("quantkit") },
  { slug: "leakguard", name: "LeakGuard", category: "ml", onAiPlatform: false,
    description: "Audits tabular datasets for data-quality defects and ML leakage - 32 detectors, each deterministic or heuristic.",
    url: "https://leakguard-site.vercel.app", screenshot: shot("leakguard") },
  { slug: "driftwatch", name: "DriftWatch", category: "ml", onAiPlatform: false,
    description: "Open-source Python library for detecting drift between two windows of data.",
    url: "https://driftwatch-docs.vercel.app", screenshot: shot("driftwatch") },
  { slug: "memory-wall", name: "Memory Wall", category: "ml", onAiPlatform: false,
    description: "Why decoding one token from a 7B model means streaming every weight out of RAM.",
    url: "https://memory-wall-liart.vercel.app", screenshot: shot("memory-wall") },
  { slug: "ai-from-scratch", name: "AI From Scratch", category: "ml", onAiPlatform: false,
    description: "Nine browser demos from minimax to agents, every algorithm implemented from scratch.",
    url: "https://ai-algorithms-from-scratch.vercel.app", screenshot: shot("ai-from-scratch") },
  { slug: "mood-ring", name: "Mood Ring", category: "ml", onAiPlatform: false,
    description: "Sentiment, zero-shot classification, and fill-mask from three pretrained models - zero training.",
    url: "https://mood-ring-theta.vercel.app", screenshot: shot("mood-ring") },
  { slug: "bottleneck-digits", name: "The Bottleneck", category: "ml", onAiPlatform: false,
    description: "Keras autoencoder that squeezes 1,797 handwritten digits into 2 numbers each.",
    url: "https://bottleneck-digits.vercel.app", screenshot: shot("bottleneck-digits") },
  { slug: "name-forge", name: "NAME FORGE", category: "ml", onAiPlatform: false,
    description: "Character-level neural name generator in one PyTorch file.",
    url: "https://name-forge-docs.vercel.app", screenshot: shot("name-forge") },
  { slug: "price-engine", name: "Price Engine", category: "ml", onAiPlatform: false,
    description: "50,000-row house-price benchmark testing LightGBM's speed claims with a stopwatch.",
    url: "https://price-engine-psi.vercel.app", screenshot: shot("price-engine") },
  { slug: "article-xray", name: "Article X-Ray", category: "ml", onAiPlatform: false,
    description: "What spaCy pulls out of a news paragraph - entities, structure, and timing from a real run.",
    url: "https://article-xray.vercel.app", screenshot: shot("article-xray") },
  { slug: "curve-fitter", name: "curve_fitter.py", category: "ml", onAiPlatform: false,
    description: "Cubic curve fit in raw TensorFlow GradientTape, with the Keras removed.",
    url: "https://curve-fitter.vercel.app", screenshot: shot("curve-fitter") },

  // --- Research ---
  { slug: "leangraph", name: "LeanGraph", category: "research", onAiPlatform: true,
    description: "Benchmark of LLM agents writing Lean 4 proofs, where a proof only counts if Lean verifies it.",
    url: "https://leangraph.vercel.app", screenshot: shot("leangraph") },
  { slug: "cortexflow", name: "CortexFlow", category: "research", onAiPlatform: false,
    description: "Classical vs. neural models forecasting mouse visual-cortex activity under strict future-time and cross-animal holdouts.",
    url: "https://cortexflow-bench.vercel.app", screenshot: shot("cortexflow") },
  { slug: "cityformgen", name: "CityFormGen", category: "research", onAiPlatform: false,
    description: "Benchmark of generative-design methods for multi-objective middle-housing layouts, with Pareto analysis.",
    url: "https://cityformgen.vercel.app", screenshot: shot("cityformgen") },
  { slug: "timemind", name: "TimeMind", category: "research", onAiPlatform: false,
    description: "Browser psychophysics platform and estimator benchmark for serial dependence in perception (simulation-only).",
    url: "https://timemind.vercel.app", screenshot: shot("timemind") },
  { slug: "darksignal", name: "DarkSignal", category: "research", onAiPlatform: false,
    description: "Measures how much real signal machine-learned systematics correction erases, with a DESI cosmology case study.",
    url: "https://darksignal-bench.vercel.app", screenshot: shot("darksignal") },
  { slug: "radevidence", name: "RadEvidence", category: "research", onAiPlatform: false,
    description: "Are AI-generated radiology research syntheses grounded in report evidence and published literature?",
    url: "https://radevidence.vercel.app", screenshot: shot("radevidence") },
  { slug: "assessai", name: "AssessAI", category: "research", onAiPlatform: true,
    description: "Do AI-generated statistics exam questions actually measure knowledge? A validity benchmark.",
    url: "https://assessai-benchmark.vercel.app", screenshot: shot("assessai") },
  { slug: "quakecast", name: "QuakeCast", category: "research", onAiPlatform: false,
    description: "Forward-in-time benchmark of classical vs. machine-learned aftershock models on fourteen real earthquake sequences.",
    url: "https://quakecast.vercel.app", screenshot: shot("quakecast") },
  { slug: "climateorbit", name: "ClimateOrbit", category: "research", onAiPlatform: false,
    description: "How much seasonal-climate variability orbital forcing explains, and how robust that is across models and scales.",
    url: "https://climateorbit.vercel.app", screenshot: shot("climateorbit") },
  { slug: "gendernews-atlas", name: "GenderNews Atlas", category: "research", onAiPlatform: false,
    description: "How robust are NLP measurements of changing gender representation in U.S. news, 1900-1963?",
    url: "https://gendernews-atlas.vercel.app", screenshot: shot("gendernews-atlas") },
  { slug: "rare-rag-bench", name: "RareRAG Bench", category: "research", onAiPlatform: false,
    description: "How reliably retrieval and RAG systems find, combine, and cite sparse evidence for rare-disease questions.",
    url: "https://rare-rag-bench.vercel.app", screenshot: shot("rare-rag-bench") },
  { slug: "soundrevive", name: "SoundRevive", category: "research", onAiPlatform: false,
    description: "Benchmark for ML restoration of degraded historical audio: does cleaner mean closer to the original?",
    url: "https://site-five-beryl-25.vercel.app", screenshot: shot("soundrevive") },
  { slug: "bioresearch-agent", name: "BioResearchAgent", category: "research", onAiPlatform: false,
    description: "Benchmark of evidence-grounded LLM agents for biological literature synthesis.",
    url: "https://bioresearch-agent.vercel.app", screenshot: shot("bioresearch-agent") },
  { slug: "cosmoscope", name: "CosmoScope", category: "research", onAiPlatform: false,
    description: "Reproducible large-scale-structure clustering and ML systematics-correction study on public DESI DR1 data.",
    url: "https://cosmoscope-eta.vercel.app", screenshot: shot("cosmoscope") },
  { slug: "biasmarket-lab", name: "BiasMarket Lab", category: "research", onAiPlatform: true,
    description: "How AI-generated product framing shapes consumer belief, choice, and market outcomes.",
    url: "https://biasmarket-lab.vercel.app", screenshot: shot("biasmarket-lab") },
  { slug: "biocluster", name: "BioCluster", category: "research", onAiPlatform: false,
    description: "Benchmark of self-supervised and unsupervised representation learning for biomedical images.",
    url: "https://site-two-nu-61.vercel.app", screenshot: shot("biocluster") },
  { slug: "folklore-vector", name: "FolkloreVector", category: "research", onAiPlatform: false,
    description: "Computational mapping of cultural change and narrative structure in the Journal of American Folklore, 1888-1930.",
    url: "https://folklore-vector.vercel.app", screenshot: shot("folklore-vector") },
  { slug: "sandwatch", name: "SandWatch", category: "research", onAiPlatform: false,
    description: "Can Sentinel-2 satellite imagery detect disturbance signatures of river sand extraction?",
    url: "https://sandwatch-xi.vercel.app", screenshot: shot("sandwatch") },
  { slug: "urbanlens-india", name: "UrbanLens India", category: "research", onAiPlatform: false,
    description: "Measuring urban infrastructure from street-level imagery in Indian cities - and how biased uneven coverage makes it.",
    url: "https://urbanlens-india.vercel.app", screenshot: shot("urbanlens-india") },
  { slug: "suspense-atlas", name: "Suspense Atlas", category: "research", onAiPlatform: false,
    description: "Measuring how suspense evolves across 92 public-domain short stories, and whether language models reproduce it.",
    url: "https://suspense-atlas.vercel.app", screenshot: shot("suspense-atlas") },
  { slug: "sagagraph", name: "SagaGraph", category: "research", onAiPlatform: false,
    description: "Audits how reliably NLP reconstructs the social networks of the Icelandic family sagas.",
    url: "https://sagagraph.vercel.app", screenshot: shot("sagagraph") },
  { slug: "floorplanbench", name: "FloorPlanBench", category: "research", onAiPlatform: false,
    description: "Compares random, greedy, annealing, NSGA-II, and constraint search for generating building floor plans.",
    url: "https://floorplanbench.vercel.app", screenshot: shot("floorplanbench") },
  { slug: "agenthep", name: "AgentHEP", category: "research", onAiPlatform: false,
    description: "Can LLM agents execute reproducible scientific data-analysis workflows? Audited on high-energy physics.",
    url: "https://site-beta-roan-12.vercel.app", screenshot: shot("agenthep") },
  { slug: "human-ai-trust-lab", name: "Human-AI Trust Lab", category: "research", onAiPlatform: false,
    description: "Pre-registered repeated-decision experiment on when people should rely on AI recommendations.",
    url: "https://web-six-cyan-oog5kc5p3u.vercel.app", screenshot: shot("human-ai-trust-lab") },
  { slug: "visual-story-benchmark", name: "Visual Story Benchmark", category: "research", onAiPlatform: false,
    description: "Benchmarking long-horizon coherence - same character, same world - in generative visual narratives.",
    url: "https://visual-story-benchmark.vercel.app", screenshot: shot("visual-story-benchmark") },
  { slug: "business-ai-observatory", name: "Business AI Observatory", category: "research", onAiPlatform: false,
    description: "Longitudinal, evidence-backed panel of commercial AI products - pricing, features, and providers over time.",
    url: "https://business-ai-observatory.vercel.app", screenshot: shot("business-ai-observatory") },
  { slug: "changeblind", name: "ChangeBlind", category: "research", onAiPlatform: false,
    description: "Browser-based behavioural experiment and research platform on slow-change blindness.",
    url: "https://changeblind.vercel.app", screenshot: shot("changeblind") },
  { slug: "surveillance-pricing-observatory", name: "Surveillance Pricing Observatory", category: "research", onAiPlatform: false,
    description: "Welfare simulator for personalized pricing, with Monte Carlo experiments and econometric recovery.",
    url: "https://surveillance-pricing-observatory.vercel.app", screenshot: shot("surveillance-pricing-observatory") },
  { slug: "specialist-model-series", name: "Specialist Model Series", category: "research", onAiPlatform: false,
    description: "LoRA domain specialists evaluated against their own base model under identical conditions.",
    url: "https://specialist-model-series.vercel.app", screenshot: shot("specialist-model-series") },
  { slug: "gradient-autopsy", name: "Gradient Autopsy", category: "research", onAiPlatform: false,
    description: "Why deep networks fail to train - 132 instrumented runs on gradient propagation in deep MLPs.",
    url: "https://gradient-autopsy.vercel.app", screenshot: shot("gradient-autopsy") },
  { slug: "earnings-whisperer", name: "Earnings Whisperer", category: "research", onAiPlatform: false,
    description: "Does semantic change in earnings calls predict volatility? An NLP x finance study.",
    url: "https://earnings-whisperer.vercel.app", screenshot: shot("earnings-whisperer") },
  { slug: "rate-shock", name: "Rate Shock", category: "research", onAiPlatform: false,
    description: "How Fed policy surprises propagate across markets - an FOMC event study.",
    url: "https://rate-shock-sigma.vercel.app", screenshot: shot("rate-shock") },
  { slug: "dead-cat-detector", name: "Dead Cat Detector", category: "research", onAiPlatform: false,
    description: "When extreme stock selloffs reverse, and when they keep falling - 14,678 events studied.",
    url: "https://dead-cat-detector.vercel.app", screenshot: shot("dead-cat-detector") },
  { slug: "closing-bell-effect", name: "Closing Bell Effect", category: "research", onAiPlatform: false,
    description: "Do extreme closing price moves persist overnight? An intraday event study.",
    url: "https://closing-bell-effect.vercel.app", screenshot: shot("closing-bell-effect") },
  { slug: "copycat-economy", name: "Copycat Economy", category: "research", onAiPlatform: false,
    description: "What happens right across the border after a minimum-wage increase? A border-county difference-in-differences study.",
    url: "https://copycat-economy.vercel.app", screenshot: shot("copycat-economy") },
  { slug: "rush-hour-roulette", name: "Rush Hour Roulette", category: "research", onAiPlatform: false,
    description: "Tail-risk study of NYC taxi travel-time reliability across 75M cleaned trips.",
    url: "https://rush-hour-roulette.vercel.app", screenshot: shot("rush-hour-roulette") },
  { slug: "one-percent-portfolio", name: "The 1% Portfolio", category: "research", onAiPlatform: false,
    description: "When estimation error beats optimisation - a Monte Carlo study of mean-variance portfolios.",
    url: "https://one-percent-portfolio.vercel.app", screenshot: shot("one-percent-portfolio") },
  { slug: "customer-404", name: "Customer 404", category: "research", onAiPlatform: false,
    description: "Survival analysis and trajectory clustering of how customers approach churn.",
    url: "https://customer-404.vercel.app", screenshot: shot("customer-404") },
  { slug: "forecast-graveyard", name: "Forecast Graveyard", category: "research", onAiPlatform: false,
    description: "When forecasting complexity loses to a naive baseline.",
    url: "https://forecast-graveyard.vercel.app", screenshot: shot("forecast-graveyard") },

  // --- No public URL: local-only, in progress, or archived ---
  { slug: "friday", name: "F.R.I.D.A.Y.", category: "apps", onAiPlatform: false, localOnly: true,
    description: "Cinematic voice-driven personal AI operating layer with a holographic orb interface.",
    url: null, screenshot: shot("friday") },
  { slug: "sports-betting-project", name: "Sports Betting Bot", category: "apps", onAiPlatform: true, localOnly: true,
    description: "CLI tool scanning prediction markets vs. sportsbook odds for positive-edge bets.",
    url: null, screenshot: shot("sports-betting-project") },
  { slug: "kinetic", name: "Kinetic", category: "apps", onAiPlatform: false, localOnly: true,
    description: "Camera-only hand-tracking controller for the Mac, no dedicated hardware required.",
    url: null, screenshot: shot("kinetic") },
  { slug: "quantdesk", name: "QuantDesk", category: "apps", onAiPlatform: true,
    description: "Multi-asset quant trade-signal and paper-trading platform spanning stocks, forex, crypto, and options.",
    url: null, screenshot: shot("quantdesk") },
  { slug: "project-lemon", name: "Lemon", category: "apps", onAiPlatform: false,
    description: "Native macOS voice-first AI assistant - hotkey, transcribe, and insert clean text into any focused field.",
    url: null, screenshot: shot("project-lemon") },
  { slug: "project-tally", name: "Project Tally", category: "apps", onAiPlatform: false,
    description: "Clean-room SwiftUI rebuild of the discontinued Tally habit-tracking app.",
    url: null, screenshot: shot("project-tally") },
  { slug: "red-light-chamber", name: "Red Light Chamber", category: "games", onAiPlatform: false,
    description: "Real-time turn-based 1v1 multiplayer Russian-roulette-style game (early prototype).",
    url: null, screenshot: shot("red-light-chamber") },
  { slug: "anibrief", name: "AniBrief", category: "platform", onAiPlatform: true, archived: true,
    description: "Daily briefing terminal for anime, manga, Japanese music, and voice-actor news.",
    url: null, screenshot: shot("anibrief") },
];

export const FEATURED_SLUGS = ["nodability", "engo", "fluent", "leangraph"];
