export interface Project {
  slug: string;
  name: string;
  description: string;
  url: string | null;
  screenshot: string | null; // path under /public/screenshots, or null
  onAiPlatform: boolean; // true if this app runs on the self-hosted AI platform
}

// Live URLs verified directly (curl'd 200, or docs cross-checked against a
// live response) while building this page, not guessed.
export const PROJECTS: Project[] = [
  // --- Running on the self-hosted AI platform (Yuu no Sekai) ---
  {
    slug: "nodability",
    name: "Nodability",
    description: "AI-chat-driven personal task organizer for a couple, with task board and calendar views.",
    url: "https://nodability.vercel.app",
    screenshot: "/screenshots/nodability.png",
    onAiPlatform: true,
  },
  {
    slug: "daily-brief",
    name: "Daily Brief",
    description: "Personal daily-briefing app aggregating weather, news, sports, stocks, crypto, and more.",
    url: "https://daily-brief-70cu7npew-garywangsmes-8349s-projects.vercel.app",
    screenshot: "/screenshots/daily-brief.png",
    onAiPlatform: true,
  },
  {
    slug: "anibrief",
    name: "AniBrief",
    description: "Daily briefing terminal for anime, manga, Japanese music, and voice-actor news.",
    url: "https://anibrief.vercel.app",
    screenshot: "/screenshots/anibrief.png",
    onAiPlatform: true,
  },
  {
    slug: "dramabrief",
    name: "DramaBrief",
    description: "Daily briefing platform for Asian dramas, stars, music, and reality TV news.",
    url: "https://dramabrief.vercel.app",
    screenshot: "/screenshots/dramabrief.png",
    onAiPlatform: true,
  },
  {
    slug: "market-brief",
    name: "Market Brief",
    description: "Personal finance-news dashboard with market, earnings/SEC, and AI/tech news plus a watchlist.",
    url: "https://market-brief.vercel.app",
    screenshot: "/screenshots/market-brief.png",
    onAiPlatform: true,
  },
  {
    slug: "engo",
    name: "Engo",
    description: "Video-first language-learning platform teaching Japanese/English through real YouTube lessons.",
    url: "https://engo-peach.vercel.app",
    screenshot: "/screenshots/engo.png",
    onAiPlatform: true,
  },
  {
    slug: "mindloop",
    name: "Mindloop",
    description: "Turns pasted notes into flashcards, adaptive quizzes, practice tests, and an AI tutor.",
    url: "https://mindloop-pink.vercel.app",
    screenshot: "/screenshots/mindloop.png",
    onAiPlatform: true,
  },
  {
    slug: "trading-professor",
    name: "Trading Professor",
    description: "Educational swing-trading research platform and paper-trading coach, built with Streamlit.",
    url: "https://trading-professor-gary.fly.dev",
    screenshot: "/screenshots/trading-professor.png",
    onAiPlatform: true,
  },

  // --- Other live projects ---
  {
    slug: "yume",
    name: "Yume",
    description: "Persistent virtual hangout room for friend groups with voice/video, camera bubbles, and drawing.",
    url: "https://yume-gray.vercel.app",
    screenshot: "/screenshots/yume.png",
    onAiPlatform: false,
  },
  {
    slug: "fantasy-league",
    name: "Fantasy League",
    description: "Multi-sport fantasy league app - draft and compete against 7 AI managers with distinct personas.",
    url: "https://fantasy-league-iota-six.vercel.app",
    screenshot: "/screenshots/fantasy-league.png",
    onAiPlatform: false,
  },
  {
    slug: "buildstrike-arena",
    name: "BuildStrike Arena",
    description: "Fast browser-based 3D 1v1 build-and-shoot duel game against a bot or a friend.",
    url: "https://buildstrike-arena.vercel.app",
    screenshot: "/screenshots/buildstrike-arena.png",
    onAiPlatform: false,
  },
  {
    slug: "hyperliquid-bot-web",
    name: "Hyperliquid Bot",
    description: "Read-only paper-trading dashboard mirroring an EMA-crossover strategy on live market data.",
    url: "https://hyperliquid-bot-web-alpha.vercel.app",
    screenshot: "/screenshots/hyperliquid-bot-web.png",
    onAiPlatform: false,
  },
  {
    slug: "sports-betting-web",
    name: "Sports Betting Scanner",
    description: "Password-gated scanner comparing sportsbook odds vs. prediction markets to flag +EV bets.",
    url: "https://sports-betting-web.vercel.app",
    screenshot: "/screenshots/sports-betting-web.png",
    onAiPlatform: false,
  },
  {
    slug: "careeratlas",
    name: "CareerAtlas",
    description: "Interactive global job salary, career-transition, education-impact, and industry-trend tracker.",
    url: "https://careeratlas.vercel.app",
    screenshot: "/screenshots/careeratlas.png",
    onAiPlatform: false,
  },
  {
    slug: "chamber-seven",
    name: "Chamber Seven",
    description: "Real-time multiplayer shotgun-duel game inspired by Buckshot Roulette, with a Career Mode.",
    url: "https://chamber-seven-omega.vercel.app",
    screenshot: "/screenshots/chamber-seven.png",
    onAiPlatform: false,
  },
  {
    slug: "vantage-chess",
    name: "Vantage Chess",
    description: "Original from-scratch online chess platform with 10 Stockfish bot personalities and variants.",
    url: "https://vantage-chess.vercel.app",
    screenshot: "/screenshots/vantage-chess.png",
    onAiPlatform: false,
  },
  {
    slug: "sound-clash",
    name: "Sound Clash",
    description: "Real-time multiplayer music-guessing party game - buzz in, name the song, steal points.",
    url: "https://sound-clash-nu.vercel.app",
    screenshot: "/screenshots/sound-clash.png",
    onAiPlatform: false,
  },
  {
    slug: "pocket-party",
    name: "Pocket Party",
    description: "Browser-based multiplayer mini-game platform - no download or account needed, just a room code.",
    url: "https://pocket-party-eta.vercel.app",
    screenshot: "/screenshots/pocket-party.png",
    onAiPlatform: false,
  },
  {
    slug: "puzzle-rush",
    name: "Puzzle Rush",
    description: "Daily puzzle platform in the spirit of Wordle/LinkedIn Games, with guest play and leaderboards.",
    url: "https://puzzle-rush.vercel.app",
    screenshot: "/screenshots/puzzle-rush.png",
    onAiPlatform: false,
  },
  {
    slug: "together-wellness",
    name: "Together Wellness",
    description: "Private app for a couple to connect Oura Ring accounts and share sleep/health data.",
    url: "https://together-wellness.vercel.app",
    screenshot: "/screenshots/together-wellness.png",
    onAiPlatform: false,
  },
  {
    slug: "full-house",
    name: "Full House",
    description: "Screen-scraping poker assistant for friendly, no-money home games.",
    url: "https://gariyuuu.github.io/full-house/",
    screenshot: "/screenshots/full-house.png",
    onAiPlatform: false,
  },
  {
    slug: "anime-sim",
    name: "ANIME//SIM",
    description: "Story-driven 2D anime life simulator blending visual novel, social-strategy, and turn-based RPG.",
    url: "https://anime-sim-eta.vercel.app",
    screenshot: "/screenshots/anime-sim.png",
    onAiPlatform: false,
  },
  {
    slug: "pocket-vlog-web",
    name: "Pocket Vlog",
    description: "Group members capture daily moments that auto-assemble into a shared vlog at a cutoff time.",
    url: "https://pocket-vlog-web.vercel.app",
    screenshot: "/screenshots/pocket-vlog-web.png",
    onAiPlatform: false,
  },
  {
    slug: "click-to-send",
    name: "Click to Send",
    description: "Tiny single-page site that sends a message by email or Discord DM via a shared access code.",
    url: "https://click-to-send.vercel.app",
    screenshot: "/screenshots/click-to-send.png",
    onAiPlatform: false,
  },
  {
    slug: "phone-watchdog-web",
    name: "Phone Watchdog",
    description: "Webcam-based app using on-device ML to detect phone use and trigger a fullscreen alarm.",
    url: "https://phone-watchdog-web.vercel.app",
    screenshot: null, // password-protected (HTTP Basic Auth), no preview available
    onAiPlatform: false,
  },

  // --- In progress / not yet deployed ---
  {
    slug: "sports-betting-project",
    name: "Sports Betting Bot",
    description: "CLI tool scanning prediction markets vs. sportsbook odds for positive-edge bets.",
    url: null,
    screenshot: null,
    onAiPlatform: true,
  },
  {
    slug: "friday",
    name: "F.R.I.D.A.Y.",
    description: "Cinematic voice-driven personal AI operating layer with a holographic orb interface.",
    url: null,
    screenshot: null,
    onAiPlatform: false,
  },
  {
    slug: "heartbreak-academy",
    name: "Heart//Break Academy",
    description: "Anime-psychological RPG with Undertale-style bullet-dodging combat and visual-novel dialogue.",
    url: null,
    screenshot: null,
    onAiPlatform: false,
  },
  {
    slug: "red-light-chamber",
    name: "Red Light Chamber",
    description: "Real-time turn-based 1v1 multiplayer Russian-roulette-style game (early prototype).",
    url: null,
    screenshot: null,
    onAiPlatform: false,
  },
];
